blog_controllers:
    resource:
        path: '@BlogBundle/src/Controller/'
        namespace: Bundle\Blog\Controller
    type: attribute

admin_controllers:
    resource:
        path: '@AdminBundle/src/Controller/'
        namespace: Bundle\Admin\Controller
    type: attribute

auth_controllers:
    resource:
        path: '@AuthBundle/src/Controller/'
        namespace: Bundle\Auth\Controller
    type: attribute