controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

blog_controllers:
    resource:
        path: '@BlogBundle/src/Controller/'
        namespace: Bundle\Blog\Controller
    type: attribute

admin_controllers:
    resource:
        path: '@AdminBundle/src/Controller/'
        namespace: Bundle\Admin\Controller
    type: attribute