# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_dir: '%kernel.project_dir%/public/images'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    
    Bundle\Blog\: # change this to your new namespace
        resource: '../bundle/Blog/src'
        exclude:
            - '../bundle/Blog/src/DependencyInjection/'
            - '../bundle/Blog/src/Entity/'
            - '../bundle/Blog/src/Kernel.php'

    Bundle\Admin\: # change this to your new namespace
        resource: '../bundle/Admin/src'
        exclude:
            - '../bundle/Admin/src/DependencyInjection/'
            - '../bundle/Admin/src/Entity/'
            - '../bundle/Admin/src/Kernel.php'

    Bundle\Auth\: # change this to your new namespace
        resource: '../bundle/Auth/src'
        exclude:
            - '../bundle/Auth/src/DependencyInjection/'
            - '../bundle/Auth/src/Entity/'
            - '../bundle/Auth/src/Kernel.php'

    Bundle\Database\: # change this to your new namespace
        resource: '../bundle/Database/src'
        exclude:
            - '../bundle/Database/src/DependencyInjection/'
            - '../bundle/Database/src/Entity/'
            - '../bundle/Database/src/Kernel.php'

    Bundle\Admin\Service\ImageService:
        arguments:
            $uploadDir: '%upload_dir%'

    # mm:
    #     alias: App\Service\MessageGenerator

    # m234:
    #     alias: App\Service\MessageGenerator234

#    App\Service\MessageGenerator:
#        arguments:
#            $adminEmail: 'manager@example.com'

    # App\Interface\AsdInterface: '@mm'
    # App\Interface\AsdInterface $m234: '@m234'

    # App\Service\MessageGenerator234:
    #     arguments:
    #         $adminEmail: 'manager@example.com'

    # App\Service\MessageGenerator:
    #     autowire: true
    #     lazy: true
    #     factory: [ !service { class: App\Factory\AsdFactory }, 'constructFoo' ]
    #     arguments:
    #         $adminEmail: 'manager@example.com'

    # App\EventListener\AsdListener:
    #     tags:
    #         - { name: asd.listener, event: asd }

    # App\EventSubscriber\AsdSubscriber:
    #     tags:
    #         - { name: asd.subscriber, event: afaf }

    # this is the service's id
    # mg:
    #     class: App\Service\MessageGenerator
    #     # you CAN still use autowiring: we just want to show what it looks like without
    #     # autowire: false
    #     # manually wire all arguments
    #     arguments:
    #         $adminEmail: 'manager@example.com'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
